/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}

import {
  Observable,
} from 'rxjs/';

declare global {

  namespace StencilComponents {
    interface GiDataProvider {
      'getData': (key: string) => Observable<any>;
      'pageContentUrl': string;
    }
  }

  interface HTMLGiDataProviderElement extends StencilComponents.GiDataProvider, HTMLStencilElement {}

  var HTMLGiDataProviderElement: {
    prototype: HTMLGiDataProviderElement;
    new (): HTMLGiDataProviderElement;
  };
  interface HTMLElementTagNameMap {
    'gi-data-provider': HTMLGiDataProviderElement;
  }
  interface ElementTagNameMap {
    'gi-data-provider': HTMLGiDataProviderElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'gi-data-provider': JSXElements.GiDataProviderAttributes;
    }
  }
  namespace JSXElements {
    export interface GiDataProviderAttributes extends HTMLAttributes {
      'pageContentUrl'?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;