/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}

import {
  Observable,
} from 'rxjs/';

declare global {

  namespace StencilComponents {
    interface GiAnimationProgressBar {

    }
  }

  interface HTMLGiAnimationProgressBarElement extends StencilComponents.GiAnimationProgressBar, HTMLStencilElement {}

  var HTMLGiAnimationProgressBarElement: {
    prototype: HTMLGiAnimationProgressBarElement;
    new (): HTMLGiAnimationProgressBarElement;
  };
  interface HTMLElementTagNameMap {
    'gi-animation-progress-bar': HTMLGiAnimationProgressBarElement;
  }
  interface ElementTagNameMap {
    'gi-animation-progress-bar': HTMLGiAnimationProgressBarElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'gi-animation-progress-bar': JSXElements.GiAnimationProgressBarAttributes;
    }
  }
  namespace JSXElements {
    export interface GiAnimationProgressBarAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface GiAnimation {
      'animation': string;
      'canvasPauseAnimation': () => void;
      'canvasPlayAnimation': () => void;
      'chapter': string;
      'imgext': string;
      'isClassroomModeOn': boolean;
      'project': string;
      'session': string;
    }
  }

  interface HTMLGiAnimationElement extends StencilComponents.GiAnimation, HTMLStencilElement {}

  var HTMLGiAnimationElement: {
    prototype: HTMLGiAnimationElement;
    new (): HTMLGiAnimationElement;
  };
  interface HTMLElementTagNameMap {
    'gi-animation': HTMLGiAnimationElement;
  }
  interface ElementTagNameMap {
    'gi-animation': HTMLGiAnimationElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'gi-animation': JSXElements.GiAnimationAttributes;
    }
  }
  namespace JSXElements {
    export interface GiAnimationAttributes extends HTMLAttributes {
      'animation'?: string;
      'chapter'?: string;
      'imgext'?: string;
      'isClassroomModeOn'?: boolean;
      'project'?: string;
      'session'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface GiComponentDataWrapper {
      'propNames': string;
      'propValues': string;
    }
  }

  interface HTMLGiComponentDataWrapperElement extends StencilComponents.GiComponentDataWrapper, HTMLStencilElement {}

  var HTMLGiComponentDataWrapperElement: {
    prototype: HTMLGiComponentDataWrapperElement;
    new (): HTMLGiComponentDataWrapperElement;
  };
  interface HTMLElementTagNameMap {
    'gi-component-data-wrapper': HTMLGiComponentDataWrapperElement;
  }
  interface ElementTagNameMap {
    'gi-component-data-wrapper': HTMLGiComponentDataWrapperElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'gi-component-data-wrapper': JSXElements.GiComponentDataWrapperAttributes;
    }
  }
  namespace JSXElements {
    export interface GiComponentDataWrapperAttributes extends HTMLAttributes {
      'propNames'?: string;
      'propValues'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface GiDataProvider {
      'baseServerUrl': string;
      'getData': (key: string) => Observable<any>;
      'pageContentUrl': string;
      'saveData': (data: any) => Observable<any>;
    }
  }

  interface HTMLGiDataProviderElement extends StencilComponents.GiDataProvider, HTMLStencilElement {}

  var HTMLGiDataProviderElement: {
    prototype: HTMLGiDataProviderElement;
    new (): HTMLGiDataProviderElement;
  };
  interface HTMLElementTagNameMap {
    'gi-data-provider': HTMLGiDataProviderElement;
  }
  interface ElementTagNameMap {
    'gi-data-provider': HTMLGiDataProviderElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'gi-data-provider': JSXElements.GiDataProviderAttributes;
    }
  }
  namespace JSXElements {
    export interface GiDataProviderAttributes extends HTMLAttributes {
      'baseServerUrl'?: string;
      'pageContentUrl'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface GiQuiz {

    }
  }

  interface HTMLGiQuizElement extends StencilComponents.GiQuiz, HTMLStencilElement {}

  var HTMLGiQuizElement: {
    prototype: HTMLGiQuizElement;
    new (): HTMLGiQuizElement;
  };
  interface HTMLElementTagNameMap {
    'gi-quiz': HTMLGiQuizElement;
  }
  interface ElementTagNameMap {
    'gi-quiz': HTMLGiQuizElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'gi-quiz': JSXElements.GiQuizAttributes;
    }
  }
  namespace JSXElements {
    export interface GiQuizAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface GiRoadmap {

    }
  }

  interface HTMLGiRoadmapElement extends StencilComponents.GiRoadmap, HTMLStencilElement {}

  var HTMLGiRoadmapElement: {
    prototype: HTMLGiRoadmapElement;
    new (): HTMLGiRoadmapElement;
  };
  interface HTMLElementTagNameMap {
    'gi-roadmap': HTMLGiRoadmapElement;
  }
  interface ElementTagNameMap {
    'gi-roadmap': HTMLGiRoadmapElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'gi-roadmap': JSXElements.GiRoadmapAttributes;
    }
  }
  namespace JSXElements {
    export interface GiRoadmapAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface GiSimpleData {
      'value': string;
    }
  }

  interface HTMLGiSimpleDataElement extends StencilComponents.GiSimpleData, HTMLStencilElement {}

  var HTMLGiSimpleDataElement: {
    prototype: HTMLGiSimpleDataElement;
    new (): HTMLGiSimpleDataElement;
  };
  interface HTMLElementTagNameMap {
    'gi-simple-data': HTMLGiSimpleDataElement;
  }
  interface ElementTagNameMap {
    'gi-simple-data': HTMLGiSimpleDataElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'gi-simple-data': JSXElements.GiSimpleDataAttributes;
    }
  }
  namespace JSXElements {
    export interface GiSimpleDataAttributes extends HTMLAttributes {
      'value'?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;